exports.palette = [
    { color: '#a59271', name: 'Gold Earth', slug: 'gold-earth' },
    { color: '#a49965', name: 'Gold Natural', slug: 'gold-natural' },
    { color: '#b59850', name: 'Gold Pure', slug: 'gold-pure' },
    { color: '#d36a67', name: 'Soft Red', slug: 'soft-red' },
    { color: '#c63e27', name: 'Rich Red', slug: 'rich-red' },
    { color: '#f26522', name: 'Bold Orange', slug: 'bold-orange' },
    { color: '#fbb034', name: 'Sun Yellow', slug: 'sun-yellow' },
    { color: '#fdd6c1', name: 'Beige', slug: 'beige' },
    { color: '#b08f49', name: 'Gold Secondary', slug: 'gold-secondary' },
    { color: '#5b5051', name: 'Charcoal', slug: 'charcoal' },
    { color: '#779da5', name: 'Grey Blue', slug: 'grey-blue' },
    { color: '#44afaa', name: 'Teal Blue', slug: 'teal-blue' },
    { color: '#a1d4ac', name: 'Moss Green', slug: 'moss-green' },
    { color: '#e6efc3', name: 'Muted Moss', slug: 'muted-moss' },
    { color: '#000', name: 'Black', slug: 'theme-black' },
    { color: '#4d4d4f', name: 'Dark Grey', slug: 'dark-grey' },
    { color: '#939598', name: 'Light Grey', slug: 'light-grey' },
    { color: '#fff', name: 'White', slug: 'theme-white' },
];
